const detail = [
  {
    id: "1",
    image: "https://pbs.twimg.com/media/GJcSzdwacAEBYp9?format=jpg&name=large",
    fullName: "Amanda Sukma",
    birthday: "17 Desember 2004",
    bloodType: "O",
    zodiac: "Sagitarius",
    height: "160cm",
    name: "Amanda",
  },
  {
    id: "2",
    image: "https://pbs.twimg.com/media/GIE_F2ZaYAAgEFi?format=jpg&name=medium",
    fullName: "Angelina Christy",
    birthday: "5 Desember 2005",
    bloodType: "O",
    zodiac: "Sagitarius",
    height: "163cm",
    name: "Christy",
  },
  {
    id: "3",
    image: "https://pbs.twimg.com/media/GQcIevXa4AAb1zJ?format=jpg&name=large",
    fullName: "Aurellia",
    birthday: "29 Oktober 2002",
    bloodType: "O",
    zodiac: "Scorpio",
    height: "155cm",
    name: "Lia",
  },
  {
    id: "4",
    image: "https://pbs.twimg.com/media/F7vrlKCawAE9E48?format=jpg&name=large",
    fullName: "Azizi Asadel",
    birthday: "16 Mei 2004",
    bloodType: "O",
    zodiac: "Taurus",
    height: "162cm",
    name: "Zee",
  },
  {
    id: "5",
    image: "https://pbs.twimg.com/media/GIavO2raYAE3Kh-?format=jpg&name=large",
    fullName: "Callista Alifia",
    birthday: "8 Agustus 2005",
    bloodType: "O",
    zodiac: "Leo",
    height: "157cm",
    name: "Callie",
  },
  {
    id: "6",
    image: "https://pbs.twimg.com/media/GG6Rs_xbwAA49y6?format=jpg&name=large",
    fullName: "Cornelia Vanisa",
    birthday: "26 Juli 2002",
    bloodType: "O",
    zodiac: "Leo",
    height: "162cm",
    name: "Oniel",
  },
  {
    id: "7",
    image: "https://pbs.twimg.com/media/GG7VcguboAAOTph?format=jpg&name=large",
    fullName: "Febriola Sinambela",
    birthday: "26 Februari 2005",
    bloodType: "B",
    zodiac: "Pisces",
    height: "154cm",
    name: "Olla",
  },
  {
    id: "8",
    image: "https://pbs.twimg.com/media/F9myMs0aYAA7lNj?format=jpg&name=large",
    fullName: "Feni Fitriyanti",
    birthday: "16 Januari 1999",
    bloodType: "O",
    zodiac: "Capricorn",
    height: "162cm",
    name: "Feni",
  },
  {
    id: "9",
    image: "https://pbs.twimg.com/media/GGcnd4ebMAEzHEQ?format=jpg&name=large",
    fullName: "Fiony Alveria",
    birthday: "4 Februari 2002",
    bloodType: "O",
    zodiac: "Aquarius",
    height: "158cm",
    name: "Fiony",
  },
  {
    id: "10",
    image: "https://pbs.twimg.com/media/E6F6bqAUYAcY13W?format=jpg&name=large",
    fullName: "Marsha Lenathea",
    birthday: "9 Januari 2006",
    bloodType: "O",
    zodiac: "Capricorn",
    height: "163cm",
    name: "Marsha",
  },
  {
    id: "11",
    image: "https://pbs.twimg.com/media/FQkqu3ZagAAD3Iv?format=jpg&name=large",
    fullName: "Freya Jayawardana",
    birthday: "13 Februari 2006",
    bloodType: "B",
    zodiac: "Aquarius",
    height: "154cm",
    name: "Freya",
  },
  {
    id: "12",
    image: "https://pbs.twimg.com/media/F3uGP6SasAAVYi7?format=jpg&name=large",
    fullName: "Gabriela Abigail",
    birthday: "7 Agustus 2006",
    bloodType: "B",
    zodiac: "Leo",
    height: "160cm",
    name: "Ella",
  },
  {
    id: "13",
    image: "https://pbs.twimg.com/media/F6zFq5wbkAAT9OI?format=jpg&name=large",
    fullName: "Gita Sekar Andarini",
    birthday: "30 Juni 2001",
    bloodType: "O",
    zodiac: "Cancer",
    height: "165cm",
    name: "Gita",
  },
  {
    id: "14",
    image: "https://pbs.twimg.com/media/GNXIcV2bIAEhk-s?format=jpg&name=large",
    fullName: "Grace Octaviani",
    birthday: "18 Oktober 2007",
    bloodType: "B",
    zodiac: "Libra",
    height: "165cm",
    name: "Gracie",
  },
  {
    id: "15",
    image: "https://pbs.twimg.com/media/GJXwUOyaEAAmBBp?format=jpg&name=large",
    fullName: "Flora Shafiq",
    birthday: "4 April 2005",
    bloodType: "B",
    zodiac: "Aries",
    height: "149cm",
    name: "Flora",
  },
  {
    id: "16",
    image:
      "https://pbs.twimg.com/media/F5j1AXAaEAAIfmL?format=jpg&name=900x900",
    fullName: "Greesella Adhalia",
    birthday: "10 Januari 2006",
    bloodType: "O",
    zodiac: "Capricorn",
    height: "165cm",
    name: "Greesel",
  },
  {
    id: "17",
    image: "https://pbs.twimg.com/media/Fa8cNZIaUAAaJFa?format=jpg&name=large",
    fullName: "Helisma Putri",
    birthday: "15 Juni 2000",
    bloodType: "A",
    zodiac: "Gemini",
    height: "165cm",
    name: "Eli",
  },
  {
    id: "18",
    image: "https://pbs.twimg.com/media/FhMJNTxUYAArDsO?format=jpg&name=large",
    fullName: "Indah Cahya",
    birthday: "20 Maret 2001",
    bloodType: "A",
    zodiac: "Pisces",
    height: "165cm",
    name: "Indah",
  },
  {
    id: "19",
    image: "https://pbs.twimg.com/media/GJI-9qNaAAAVetg?format=jpg&name=large",
    fullName: "Indira Seruni",
    birthday: "26 April 2004",
    bloodType: "A",
    zodiac: "Taurus",
    height: "160cm",
    name: "Indira",
  },
  {
    id: "20",
    image: "https://pbs.twimg.com/media/F8iQmCHbcAAk1sE?format=jpg&name=large",
    fullName: "Jessica Chandra",
    birthday: "23 September 2005",
    bloodType: "O",
    zodiac: "Libra",
    height: "163cm",
    name: "Jessi",
  },
  {
    id: "21",
    image: "https://pbs.twimg.com/media/F80FlpFbYAAys7I?format=jpg&name=large",
    fullName: "Jesslyn Elly",
    birthday: "13 September 2001",
    bloodType: "O",
    zodiac: "Virgo",
    height: "155cm",
    name: "Lyn",
  },
  {
    id: "22",
    image: "https://pbs.twimg.com/media/GNUAZf1aQAADE87?format=jpg&name=large",
    fullName: "Kathrina Irene",
    birthday: "26 Juli 2006",
    bloodType: "A",
    zodiac: "Leo",
    height: "165cm",
    name: "Kathrina",
  },
  {
    id: "23",
    image: "https://pbs.twimg.com/media/GDk6PZEa4AEKAiz?format=jpg&name=large",
    fullName: "Lulu Salsabila",
    birthday: "23 Oktober 2002",
    bloodType: "B",
    zodiac: "Scorpio",
    height: "157cm",
    name: "Lulu",
  },
  {
    id: "24",
    image: "https://pbs.twimg.com/media/GGyUG6JWcAAKPZ8?format=jpg&name=large",
    fullName: "Mutiara Azzahra",
    birthday: "12 Juli 2004",
    bloodType: "B",
    zodiac: "Cancer",
    height: "158cm",
    name: "Muthe",
  },
  {
    id: "25",
    image: "https://pbs.twimg.com/media/FlyUR6VagAA7Zmw?format=jpg&name=large",
    fullName: "Raisha Syifa",
    birthday: "11 November 2007",
    bloodType: "AB",
    zodiac: "Scorpio",
    height: "163cm",
    name: "Raisha",
  },
  {
    id: "26",
    image: "https://pbs.twimg.com/media/Fxn90I5X0AMYF_I?format=jpg&name=large",
    fullName: "Reva Fidela",
    birthday: "14 Juli 2006",
    bloodType: "A",
    zodiac: "Cancer",
    height: "159cm",
    name: "Adel",
  },
  {
    id: "27",
    image: "https://pbs.twimg.com/media/F0w7G_1aEAIIrW1?format=jpg&name=large",
    fullName: "Shani Indira Natio",
    birthday: "5 Oktober 1998",
    bloodType: "B",
    zodiac: "Libra",
    height: "167cm",
    name: "Shani",
  },
  {
    id: "28",
    image: "https://pbs.twimg.com/media/FpuV7twakAIZgOj?format=jpg&name=large",
    fullName: "Shania Gracia",
    birthday: "31 Agustus 1999",
    bloodType: "A",
    zodiac: "Virgo",
    height: "161cm",
    name: "Gracia",
  },
  {
    id: "29",
    image: "https://pbs.twimg.com/media/GEWN48laYAA0nfK?format=jpg&name=large",
    fullName: "Abigail Rachel",
    birthday: "6 Agustus 2008",
    bloodType: "B",
    zodiac: "Leo",
    height: "161cm",
    name: "Aralie",
  },
  {
    id: "30",
    image: "https://pbs.twimg.com/media/GQXYAIqb0AETWSr?format=jpg&name=large",
    fullName: "Adeline Wijaya",
    birthday: "1 September 2007",
    bloodType: "B",
    zodiac: "Virgo",
    height: "167cm",
    name: "Delynn",
  },
  {
    id: "31",
    image: "https://pbs.twimg.com/media/GF4XWekaAAAsDFi?format=jpg&name=large",
    fullName: "Victoria Kimberly",
    birthday: "8 Maret 2010",
    bloodType: "AB",
    zodiac: "Pisces",
    height: "158cm",
    name: "Kimmy",
  },
  {
    id: "32",
    image: "https://pbs.twimg.com/media/GKWTQ1qa8AAuN8_?format=jpg&name=large",
    fullName: "Alya Amanda",
    birthday: "26 Agustus 2006",
    bloodType: "A",
    zodiac: "Virgo",
    height: "165cm",
    name: "Alya",
  },
  {
    id: "33",
    image: "https://pbs.twimg.com/media/GKt-Lhdb0AAtQ68?format=jpg&name=large",
    fullName: "Anindya Ramadhani",
    birthday: "18 Oktober 2005",
    bloodType: "O",
    zodiac: "Libra",
    height: "154cm",
    name: "Anindya",
  },
  {
    id: "34",
    image: "https://pbs.twimg.com/media/GQhiHlUaYAAp5ui?format=jpg&name=large",
    fullName: "Aurhel Alana",
    birthday: "14 September 2006",
    bloodType: "-",
    zodiac: "Virgo",
    height: "163cm",
    name: "Lana",
  },
  {
    id: "35",
    image: "https://pbs.twimg.com/media/GL_wa2mbIAEKcoc?format=jpg&name=large",
    fullName: "Catherina Vallencia",
    birthday: "21 Agustus 2007",
    bloodType: "B",
    zodiac: "Leo",
    height: "163cm",
    name: "Erine",
  },
  {
    id: "36",
    image: "https://pbs.twimg.com/media/GK0OjdzbIAAI3Qv?format=jpg&name=large",
    fullName: "Cathleen Nixie",
    birthday: "28 Mei 2009",
    bloodType: "A",
    zodiac: "Gemini",
    height: "158cm",
    name: "Cathy",
  },
  {
    id: "37",
    image: "https://pbs.twimg.com/media/GQKrTg7aAAEgJQ8?format=jpg&name=large",
    fullName: "Celline Thefani",
    birthday: "9 April 2007",
    bloodType: "O",
    zodiac: "Aries",
    height: "163cm",
    name: "Elin",
  },
  {
    id: "38",
    image: "https://pbs.twimg.com/media/F6ts8zJbMAAt4ea?format=jpg&name=large",
    fullName: "Chelsea Davina",
    birthday: "23 Desember 2009",
    bloodType: "B",
    zodiac: "Capricorn",
    height: "168cm",
    name: "Chelsea",
  },
  {
    id: "39",
    image: "https://pbs.twimg.com/media/GN1CHaqboAEKk84?format=jpg&name=large",
    fullName: "Cynthia Yaputera",
    birthday: "22 November 2003",
    bloodType: "O",
    zodiac: "Sagitarius",
    height: "158cm",
    name: "Cynthia",
  },
  {
    id: "40",
    image: "https://pbs.twimg.com/media/GPkBbMlawAAvTnI?format=jpg&name=medium",
    fullName: "Dena Natalia",
    birthday: "16 Desember 2005",
    bloodType: "O",
    zodiac: "Sagitarius",
    height: "162cm",
    name: "Danella",
  },
  {
    id: "41",
    image: "https://pbs.twimg.com/media/GOhEpTRaoAAioUP?format=jpg&name=large",
    fullName: "Desy Natalia",
    birthday: "16 Desember 2005",
    bloodType: "O",
    zodiac: "Sagitarius",
    height: "165cm",
    name: "Daisy",
  },
  {
    id: "42",
    image: "https://pbs.twimg.com/media/GQXgrL4a0AE7nIT?format=jpg&name=large",
    fullName: "Fritzy Rosmerian",
    birthday: "28 Juli 2008",
    bloodType: "A",
    zodiac: "Leo",
    height: "157cm",
    name: "Fritzy",
  },
  {
    id: "43",
    image: "https://pbs.twimg.com/media/GN8Is7WaoAAv65A?format=jpg&name=large",
    fullName: "Gendis Mayrannisa",
    birthday: "23 Juni 2010",
    bloodType: "B",
    zodiac: "Cancer",
    height: "160cm",
    name: "Gendis",
  },
  {
    id: "44",
    image: "https://pbs.twimg.com/media/GJ6hNOtb0AAr1Jo?format=jpg&name=large",
    fullName: "Hillary Abigail",
    birthday: "19 Oktober 2007",
    bloodType: "O",
    zodiac: "Libra",
    height: "160cm",
    name: "Lily",
  },
  {
    id: "45",
    image:
      "https://pbs.twimg.com/media/GG2lOvdbwAAGyfP?format=jpg&name=900x900",
    fullName: "Jazzlyn Trisha",
    birthday: "16 Februari 2011",
    bloodType: "O",
    zodiac: "Aquarius",
    height: "164cm",
    name: "Trisha",
  },
  {
    id: "46",
    image: "https://pbs.twimg.com/media/GHwblZUbEAAa284?format=jpg&name=large",
    fullName: "Shabilqis Naila",
    birthday: "1 September 2008",
    bloodType: "B",
    zodiac: "Virgo",
    height: "160cm",
    name: "Nala",
  },
  {
    id: "47",
    image: "https://pbs.twimg.com/media/GNIshQMaEAAp9QO?format=jpg&name=large",
    fullName: "Letycia Moreen",
    birthday: "7 Juni 2010",
    bloodType: "O",
    zodiac: "Gemini",
    height: "160cm",
    name: "Moreen",
  },
  {
    id: "48",
    image: "https://pbs.twimg.com/media/F_JJFQiaoAAQVhi?format=jpg&name=large",
    fullName: "Michelle Alexandra",
    birthday: "22 April 2009",
    bloodType: "O",
    zodiac: "Taurus",
    height: "160cm",
    name: "Michie",
  },
  {
    id: "49",
    image: "https://pbs.twimg.com/media/GPnl-eSakAAOvsP?format=jpg&name=large",
    fullName: "Michelle Levia",
    birthday: "24 Januari 2009",
    bloodType: "O",
    zodiac: "Aquarius",
    height: "168cm",
    name: "Levi",
  },
  {
    id: "50",
    image: "https://pbs.twimg.com/media/GPOclcqacAAXvc1?format=jpg&name=large",
    fullName: "Nayla Suji",
    birthday: "18 Juni 2007",
    bloodType: "AB",
    zodiac: "Gemini",
    height: "161cm",
    name: "Nayla",
  },
  {
    id: "51",
    image: "https://pbs.twimg.com/media/GPkEpDIbUAAbWoM?format=jpg&name=large",
    fullName: "Nina Tutachia",
    birthday: "16 Oktober 2009",
    bloodType: "O",
    zodiac: "Libra",
    height: "162cm",
    name: "Nachia",
  },
  {
    id: "52",
    image: "https://pbs.twimg.com/media/GJ7sc-8a4AAMqpV?format=jpg&name=large",
    fullName: "Oline Manuel",
    birthday: "3 November 2007",
    bloodType: "B",
    zodiac: "Scorpio",
    height: "167cm",
    name: "Oline",
  },
  {
    id: "53",
    image: "https://pbs.twimg.com/media/GPhdrlvbUAAld3m?format=jpg&name=large",
    fullName: "Regina Wilian",
    birthday: "10 Desember 2009",
    bloodType: "B",
    zodiac: "Sagitarius",
    height: "169cm",
    name: "Regie",
  },
  {
    id: "54",
    image: "https://pbs.twimg.com/media/GRAKWSPb0AAlvET?format=jpg&name=large",
    fullName: "Ribka Budiman",
    birthday: "13 Januari 2009",
    bloodType: "O",
    zodiac: "Capricorn",
    height: "163cm",
    name: "Ribka",
  },
];

export default detail;
